name			= "Zeus Jukebox";					        // Name of your mod
author			= "Eludage";				                // Affects Arma 3 Launcher, when the mod are loaded as local
logo			= "zeusjukebox_logo.paa";			        // Logo displayed in the main menu
logoOver		= "zeusjukebox_logo.paa";	        // When the mouse is over, in the main menu
tooltip			= "Zeus Jukebox";
tooltipOwned	= "Zeus Jukebox Owned";				        // Tool tip displayed when the mouse is left over, in the main menu
picture			= "zeusjukebox_title_image.paa";		    // Picture displayed from the expansions menu. Optimal size is 2048x1024
actionName		= "GitHub";
action			= "https://github.com/Eludage/zeus-jukebox";	// Website URL, that can be accessed from the expansions menu
overview		= "A client-side Zeus module for managing and playing music.";	// Supports structured text
hideName		= 0;						                // Hide the extension name
hidePicture		= 0;						                // Hide the extension menu
dlcColor[]		= { 0.23, 0.39, 0.30, 1 };	                // Color used for DLC stripes and backgrounds (RGBA)
logoSmall		= "zeusjukebox_logo.paa";		            // Display in creative lists, next to the entities added by the mod